# Generated by Django 4.1.4 on 2022-12-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccounttable',
            name='phoneNumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customeraccounttable',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='customeraccounttable',
            name='roles',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
