# Generated by Django 4.1.4 on 2022-12-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_customeraccounttable_phonenumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccounttable',
            name='datejoined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customeraccounttable',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
