# Generated by Django 4.1.4 on 2022-12-22 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounts', '0003_customeraccounttable_datejoined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraccounttable',
            name='datejoined',
        ),
        migrations.AlterField(
            model_name='customeraccounttable',
            name='roles',
            field=models.CharField(choices=[('customer', 'customer'), ('admin', 'staff'), ('creater', 'contentCreater')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customeraccounttable',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
