# Generated by Django 4.1.4 on 2022-12-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_remove_customeraccounttable_datejoined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccounttable',
            name='Companycode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
