# Generated by Django 4.1.4 on 2023-02-24 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounts', '0006_contentcreater_delete_customeraccounttable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentcreater',
            old_name='Companycode',
            new_name='companyNumber',
        ),
        migrations.CreateModel(
            name='StaffTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePicture', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('roles', models.CharField(choices=[('Sales', 'Sales Team'), ('Markerting', 'Markerting Team'), ('Super', 'Super User')], max_length=50, null=True)),
                ('phoneNumber', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('Companycode', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
