# Generated by Django 4.1.4 on 2023-03-18 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounts', '0008_nitacagrausers_remove_contentcreater_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentcreater',
            name='user',
        ),
        migrations.AddField(
            model_name='nitacagrausers',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
