# Generated by Django 4.1.4 on 2023-04-22 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounts', '0010_rename_user_nitacagrausers_personalinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentcreater',
            name='userInfo',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='userInfo',
        ),
        migrations.RemoveField(
            model_name='nitacagrausers',
            name='logInRole',
        ),
        migrations.RemoveField(
            model_name='stafftable',
            name='profilePicture',
        ),
        migrations.RemoveField(
            model_name='stafftable',
            name='userInfo',
        ),
        migrations.AddField(
            model_name='contentcreater',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.nitacagrausers'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.nitacagrausers'),
        ),
        migrations.AlterField(
            model_name='nitacagrausers',
            name='nitacagraName',
            field=models.CharField(blank=True, choices=[('customer', 'customer'), ('admin', 'Admin'), ('creater', 'contentCreater')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nitacagrausers',
            name='personalInfo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Personal Infomation'),
        ),
        migrations.AlterField(
            model_name='nitacagrausers',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to='Pictures'),
        ),
        migrations.AlterField(
            model_name='stafftable',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.nitacagrausers'),
        ),
    ]
