# Generated by Django 4.1.4 on 2023-06-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_remove_contentcreater_userinfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerWithoutAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('PhoneNumber', models.IntegerField()),
                ('Deposit', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='customers',
        ),
    ]
