# Generated by Django 4.1.4 on 2023-04-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MVFarmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('chicken', 'Chickens')], max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='problems',
            name='numberAffected',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='problems',
            name='priority',
            field=models.CharField(choices=[('High', 'High Priority'), ('Medium', 'Medium Priority'), ('Low', 'Low Priority')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='problems',
            name='Solution',
            field=models.ManyToManyField(null=True, to='MVFarmers.solutions'),
        ),
        migrations.AddField(
            model_name='problems',
            name='animal',
            field=models.ManyToManyField(null=True, to='MVFarmers.animals'),
        ),
    ]
