# Generated by Django 4.1.4 on 2023-04-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MVFarmers', '0002_animals_solutions_problems_numberaffected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='Solution',
            field=models.ManyToManyField(to='MVFarmers.solutions'),
        ),
        migrations.AlterField(
            model_name='problems',
            name='animal',
            field=models.ManyToManyField(to='MVFarmers.animals'),
        ),
    ]
