# Generated by Django 4.1.4 on 2023-07-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisment',
            name='section',
        ),
        migrations.AlterField(
            model_name='advertisment',
            name='Homebutton',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='advertisment',
            name='disc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertisment',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
