# Generated by Django 4.1.4 on 2023-08-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_advertisment_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='didYouKnow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, upload_to='pics')),
                ('link', models.TextField(null=True)),
                ('service', models.CharField(choices=[('cosmo', 'Consmotology'), ('soft', 'SOftware'), ('hair', 'Hair Dressing')], max_length=50, null=True, verbose_name='Service Offered')),
            ],
        ),
    ]
