# Generated by Django 4.1.4 on 2023-08-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_didyouknow'),
    ]

    operations = [
        migrations.AddField(
            model_name='didyouknow',
            name='date',
            field=models.DateField(auto_now=True, verbose_name=''),
        ),
    ]
