# Generated by Django 4.1.4 on 2023-06-12 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0012_customerwithoutaccount_delete_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detailed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Custom', max_length=50)),
                ('Price', models.DecimalField(decimal_places=2, default=50.0, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Functionality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlackFunc', models.CharField(max_length=60, null=True)),
                ('BlueFunc', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='servicesTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='Pictures')),
                ('Discription', models.TextField(max_length=150, null=True)),
                ('specialOffer', models.BooleanField(default=False, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('DetailedDisc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ourservices.detailed')),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReceiveDate', models.DateTimeField(blank=True, null=True)),
                ('SubmitDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.customerwithoutaccount')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ourservices.servicestable')),
            ],
        ),
        migrations.AddField(
            model_name='detailed',
            name='Functionality',
            field=models.ManyToManyField(to='Ourservices.functionality'),
        ),
    ]
