# Generated by Django 4.1.4 on 2023-06-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ourservices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='functionality',
            old_name='BlueFunc',
            new_name='HostDays',
        ),
        migrations.RenameField(
            model_name='functionality',
            old_name='BlackFunc',
            new_name='Pages',
        ),
        migrations.AddField(
            model_name='functionality',
            name='HostPlaform',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='functionality',
            name='Responsive',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='functionality',
            name='SEO',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='functionality',
            name='SocialMedia',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
