# Generated by Django 4.1.1 on 2022-11-29 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ourservices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='FirstName',
            new_name='FullName',
        ),
    ]
