# Generated by Django 4.1.4 on 2023-06-16 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ourservices', '0002_rename_bluefunc_functionality_hostdays_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailed',
            old_name='Name',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='servicestable',
            name='DetailedDisc',
        ),
        migrations.AddField(
            model_name='detailed',
            name='service',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ourservices.servicestable'),
        ),
        migrations.AddField(
            model_name='detailed',
            name='specialOffer',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.RemoveField(
            model_name='detailed',
            name='Functionality',
        ),
        migrations.AddField(
            model_name='detailed',
            name='Functionality',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ourservices.functionality'),
        ),
    ]
