# Generated by Django 4.1.1 on 2022-12-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ourservices', '0002_rename_firstname_customers_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicesTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('pic', models.ImageField(blank=True, upload_to='pics')),
                ('briefDisc', models.TextField()),
                ('FullDisc', models.TextField()),
                ('oldPrice', models.CharField(blank=True, max_length=10)),
                ('newPrice', models.CharField(max_length=10)),
                ('specialOffer', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='customers',
            name='Service',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='SubmitDate',
        ),
    ]
