# Generated by Django 4.1.4 on 2023-06-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ourservices', '0003_rename_name_detailed_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestable',
            name='name',
            field=models.CharField(choices=[('web', 'Web Development'), ('blogHost', 'Free Blog Hosting'), ('staticsites', 'Static Websites')], max_length=50, null=True),
        ),
    ]
