# Generated by Django 4.1.1 on 2022-12-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ourservices', '0003_servicestable_remove_customers_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=30)),
                ('orderNumber', models.IntegerField()),
                ('Service', models.CharField(max_length=50)),
                ('ReceiveDate', models.DateTimeField()),
                ('SubmitDate', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='customers',
            name='ReceiveDate',
        ),
    ]
