# Generated by Django 4.1.4 on 2023-06-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ourservices', '0004_alter_servicestable_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestable',
            name='picture',
            field=models.ImageField(blank=True, height_field=50, null=True, upload_to='Pictures', verbose_name='Picture', width_field=50),
        ),
    ]
