# Generated by Django 4.1.1 on 2022-12-04 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ourservices', '0004_order_remove_customers_receivedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestable',
            name='FullDisc',
            field=models.TextField(max_length=90),
        ),
        migrations.AlterField(
            model_name='servicestable',
            name='briefDisc',
            field=models.TextField(max_length=90),
        ),
    ]
