# Generated by Django 4.1.1 on 2022-12-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ourservices', '0005_alter_servicestable_fulldisc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestable',
            name='FullDisc',
            field=models.TextField(max_length=160),
        ),
    ]
