# Generated by Django 4.1.4 on 2023-06-17 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ourservices', '0005_alter_servicestable_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicestable',
            name='DetailedDisc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ourservices.detailed'),
        ),
        migrations.AlterField(
            model_name='servicestable',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='Pictures', verbose_name='Picture'),
        ),
    ]
