# Generated by Django 4.1.4 on 2023-07-05 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ourservices', '0006_servicestable_detaileddisc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailed',
            name='Functionality',
        ),
        migrations.RemoveField(
            model_name='servicestable',
            name='DetailedDisc',
        ),
    ]
