# Generated by Django 4.1.1 on 2022-12-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ourservices', '0006_alter_servicestable_fulldisc'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='PhoneNumber',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='FullName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ReceiveDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Service',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='SubmitDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='section',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='servicestable',
            name='FullDisc',
            field=models.TextField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='servicestable',
            name='briefDisc',
            field=models.TextField(max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='servicestable',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='servicestable',
            name='newPrice',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicestable',
            name='section',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
