# Generated by Django 4.1.4 on 2023-07-05 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ourservices', '0007_remove_detailed_functionality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailed',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ourservices.servicestable', verbose_name='services table'),
        ),
    ]
