# Generated by Django 4.1.1 on 2022-12-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ourservices', '0008_alter_order_receivedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='Location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
