# Generated by Django 4.1.1 on 2022-12-08 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ourservices', '0010_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Service',
        ),
        migrations.RemoveField(
            model_name='order',
            name='section',
        ),
        migrations.AddField(
            model_name='order',
            name='serviceTable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ourservices.servicestable'),
        ),
    ]
