# Generated by Django 4.1.1 on 2022-12-08 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ourservices', '0011_remove_order_service_remove_order_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='serviceTable',
        ),
    ]
