# Generated by Django 4.1.1 on 2022-12-08 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ourservices', '0012_remove_order_servicetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='section',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='serviceTable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ourservices.servicestable'),
        ),
    ]
