# Generated by Django 4.1.1 on 2022-12-08 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ourservices', '0013_order_section_order_servicetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='section',
        ),
    ]
