# Generated by Django 4.1.1 on 2022-12-08 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ourservices', '0017_order_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='section',
        ),
    ]
