# Generated by Django 4.1.4 on 2022-12-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ourservices', '0020_alter_servicestable_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='Account',
            field=models.BooleanField(default=False),
        ),
    ]
