# Generated by Django 4.1.4 on 2023-03-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ourservices', '0023_alter_servicestable_options_servicestable_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='Account',
            field=models.CharField(choices=[('Yes', 'Create an Account'), ('No', 'Do Not Create an Account')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='SubmitDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
