# Generated by Django 4.1.4 on 2023-03-18 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_nitacagrausers_remove_contentcreater_location_and_more'),
        ('Ourservices', '0024_alter_customers_account_alter_order_submitdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.customers'),
        ),
        migrations.DeleteModel(
            name='customers',
        ),
    ]
