# Generated by Django 4.1.4 on 2022-12-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrialProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='pics')),
            ],
        ),
    ]
